runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  secure: always

env_variables:
  REDIRECT_MAIN: "https://antoniomika.me"
  EDITOR_HOSTNAME: "e.mik.qa"
  SESSION_NAME: "MainSession"
  SESSION_SECRET: "SessionSecret"
  ADMIN_EMAIL: "s@mik.qa"
  ADMIN_PASS: "AdminPass"
  FIREBASE_APIKEY: ""
  FIREBASE_AUTHDOMAIN: ""
  FIREBASE_DATABASEURL: ""
  FIREBASE_PROJECTID: ""
  FIREBASE_STORAGEBUCKET: ""
  FIREBASE_MESSAGINGSENDERID: ""